//HintName: GeneratedViewBindingAttribute.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

namespace ViewBindings.SourceGenerator.Attributes;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.AttributeUsage(global::System.AttributeTargets.Class)]
public class ViewBindingAttribute : global::System.Attribute
{
    public global::System.Type? ViewType { get; set; }
}