//HintName: GeneratedViewBindings.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using System;
using System.Windows;

namespace ViewBindings.SourceGenerator.Demo.Resources;
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public class GeneratedViewBindings : ResourceDictionary
{
    public GeneratedViewBindings()
    {
        AddDataTemplate(typeof(ViewBindings.SourceGenerator.Demo.ViewModels.FirstViewModel), typeof(ViewBindings.SourceGenerator.Demo.Views.FirstView));
    }

    void AddDataTemplate(Type viewModel, Type view)
    {
        var dataTemplate = new DataTemplate(viewModel)
        {VisualTree = new FrameworkElementFactory(view)};
        Add(new DataTemplateKey(viewModel), dataTemplate);
    }
}